#!/bin/bash
# Deploy Micro-Bet Contract to Linera Conway Testnet

set -e

echo "🌪️ StormCast - Deploy Micro-Bet Contract"
echo "=========================================="

# Navigate to project directory
cd "$(dirname "$0")"

# Check if linera is installed
if ! command -v linera &> /dev/null; then
    echo "❌ Linera CLI not found!"
    echo "Install it with: curl -fsSL https://raw.githubusercontent.com/linera-io/linera-protocol/main/scripts/install-linera.sh | bash"
    exit 1
fi

# Show wallet info
echo ""
echo "📋 Wallet Info:"
linera wallet show

echo ""
echo "📦 Building contracts..."

# Navigate to examples
cd linera-conway/examples

# Build the contracts
cargo build --release --target wasm32-unknown-unknown -p fungible -p micro-bet

echo ""
echo "✅ Build complete!"

echo ""
echo "🚀 Deploying Fungible Token App..."

# Deploy fungible token
FUNGIBLE_APP_ID=$(linera project publish-and-create fungible \
  --json-argument '{"accounts": {}}' \
  --json-parameters '{}' 2>&1 | tail -1)

echo "Fungible App ID: $FUNGIBLE_APP_ID"

echo ""
echo "🚀 Deploying Micro-Bet App..."

# Deploy micro-bet
MICRO_BET_APP_ID=$(linera project publish-and-create micro-bet \
  --json-argument "{\"fungible_app_id\": \"$FUNGIBLE_APP_ID\", \"_dummy\": null}" \
  --json-parameters "\"$FUNGIBLE_APP_ID\"" 2>&1 | tail -1)

echo "Micro-Bet App ID: $MICRO_BET_APP_ID"

# Get chain ID
CHAIN_ID=$(linera wallet show --json 2>/dev/null | grep -o '"default": "[^"]*"' | cut -d'"' -f4)

echo ""
echo "✅ Deployment complete!"
echo ""
echo "======================================"
echo "📋 SAVE THESE VALUES FOR FRONTEND:"
echo "======================================"
echo ""
echo "NEXT_PUBLIC_CHAIN_ID=$CHAIN_ID"
echo "NEXT_PUBLIC_MICRO_BET_APP_ID=$MICRO_BET_APP_ID"
echo ""
echo "======================================"

# Save to env file
cd ../..
cat > .env.linera << EOF
# Linera Configuration
# Generated by deploy-micro-bet.sh

CHAIN_ID=$CHAIN_ID
FUNGIBLE_APP_ID=$FUNGIBLE_APP_ID
MICRO_BET_APP_ID=$MICRO_BET_APP_ID
EOF

echo "✅ Saved to .env.linera"
echo ""
echo "Next steps:"
echo "1. Copy the values above to frontend/.env.local"
echo "2. Run: ./start-linera-service.sh"
echo "3. In another terminal, start the frontend: cd frontend && npm run dev"
