{
 "title": "Alternator",
 "tags": [ "6.2" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "by",
    "label": "by",
    "query": "Cluster : cluster,DC : dc, Instance : instance, Shard : instance\\,shard"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(scylla_reactor_utilization, cluster)"
   },
   {
    "name": "dc",
    "label": "dc",
    "query": "label_values(scylla_reactor_utilization{cluster=~\"$cluster\"}, dc)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(scylla_reactor_utilization{cluster=~\"$cluster|$^\", dc=~\"$dc\"}, instance)"
   },
   {
    "name": "shard",
    "label": "shard",
    "query": "label_values(scylla_reactor_utilization,shard)"
   },
   { "name": "mount_point", "label": "Mount path", "query": "node_filesystem_avail_bytes" },
   { "name": "func", "label": "Function", "query": "sum,avg,max,min,stddev,stdvar" },
   { "name": "dash_version", "query": "6-2" },
   { "name": "scylla_version", "query": "6.2" },
   { "name": "monitoring_version", "query": "4.9.4" },
   {
    "name": "alternator_latency_ops",
    "query": "GetItem,PutItem,UpdateItem,DeleteItem,BatchWriteItem,BatchGetItem"
   },
   { "name": "alternator_streams_latency_ops", "query": "GetRecords" },
   {
    "name": "ops",
    "label": "ops",
    "query": "label_values(scylla_alternator_operation{cluster=~\"$cluster|$\"},op)"
   },
   {
    "name": "no_alternator",
    "query": {
     "query": "scylla_alternator_total_operations{cluster=~\"$cluster|$^\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Alternator Cluster overview $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://repositories.scylladb.com/scylla/imgversion/$monitoring_version/scylla-monitoring\">"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Manager",
   "type": "text",
   "gridPos": { "h": 1, "w": 3, "x": 6, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average latencies",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 9, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "P99 Latencies",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 13, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 7, "x": 17, "y": 1 },
   "options": { "content": "# " },
   "targets": [
    {}
   ]
  },
  {
   "title": "# Nodes",
   "type": "stat",
   "description": "The number of nodes configured in the cluster.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(scylla_scylladb_current_version{job=\"scylla\", cluster=\"$cluster\"})",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "Unreachable",
   "type": "stat",
   "description": "The number of unreachable nodes.\nUsually because a machine is down or unreachable.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(count(scrape_samples_scraped{job=\"scylla\", cluster=\"$cluster\"}==0) OR vector(0))",
     "legendFormat": "Offline "
    }
   ]
  },
  {
   "title": "Inactive",
   "type": "stat",
   "description": "The number of joining and leaving nodes.\nThe number of nodes that are up but not actively part of the cluster, either because they are still joining or because they are leaving.",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(scylla_node_operation_mode{cluster=\"$cluster\"}!=3)OR vector(0)",
     "legendFormat": "Offline "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(scylla_manager_scheduler_run_indicator{type=~\"repair\",cluster=\"$cluster\"}) or on() vector(0)) + (max(scylla_manager_scheduler_run_indicator{type=~\"backup\",cluster=\"$cluster\"})*2 or on() vector(0)) + (sum(scylla_manager_server_current_version{}) or on() vector(-1))"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 1, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(avg(scylla_manager_repair_progress{cluster=\"$cluster\", job=\"scylla_manager\"}) * max(scylla_manager_scheduler_run_indicator{type=\"repair\",cluster=\"$cluster\"})) or on ()  (100*avg(manager:backup_progress{cluster=\"$cluster\"}) * max(scylla_manager_scheduler_run_indicator{type=\"backup\",cluster=\"$cluster\"})) or on () vector(0)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(scylla_alternator_op_latency_sum{cluster=~\"$cluster\", op=~\"$ops\"}[$__rate_interval])) by (op)/sum(rate(scylla_alternator_op_latency_count{cluster=~\"$cluster|^$\", op=~\"$ops\"}[$__rate_interval])>0) by (op)",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_alternator_op_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=~\"$ops\"}[$__rate_interval])>0) by (op, le))",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Total Operations/s",
   "type": "stat",
   "description": "Total Operations per seconds",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "si:" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dashversion": [
      ">6.2",
      ">2025.1"
     ],
     "expr": "(sum(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\", op !~\"Batch.*\"}[$__rate_interval])) or vector(0))+ on() (sum(rate(scylla_alternator_batch_item_count{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) or vector(0))"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "description": "The percentage of the time during which Scylla utilized the CPU. Note that because Scylla does busy polling for some time before going idle, CPU utilization as seen by the operating system may be much higher. Your system is not yet CPU-bottlenecked until this metric is high.",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(scylla_reactor_utilization{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"} )"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "stat",
   "description": "The rate of timeouts (read and write).\n\nTimeouts are an indication of an overloaded system",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(rate(scylla_storage_proxy_coordinator_write_timeouts{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) or on() vector(0)) + (sum(rate(scylla_storage_proxy_coordinator_read_timeouts{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) or on() vector(0))"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Cluster Storage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=\"$mount_point\", instance=~\"$node\"})-sum(node_filesystem_avail_bytes{mountpoint=\"$mount_point\", instance=~\"$node\"})",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "sum(node_filesystem_size{mountpoint=\"$mount_point\", instance=~\"$node\"})-sum(node_filesystem_avail{mountpoint=\"$mount_point\", instance=~\"$node\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Operations/s",
   "type": "timeseries",
   "description": "Number of Alternator Operations by operation type",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\", op=~\"$ops\"}[$__rate_interval])>0) by (op)",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "P95 Latencies",
   "type": "timeseries",
   "description": "The P95 Latencies per operation",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(scylla_alternator_op_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=~\"$ops\"}[$__rate_interval])>0) by (op, le))",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "P99 Latencies",
   "type": "timeseries",
   "description": "The P99 Latencies per operation",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_alternator_op_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=~\"$ops\"}[$__rate_interval])>0) by (op, le))",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "dc",
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "options": {
    "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Information for $dc</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "0*scylla_scylladb_current_version{cluster=\"$cluster\", dc=~\"$dc\"} + on (instance) group_left() (scylla_node_operation_mode{cluster=\"$cluster\", dc=~\"$dc\"}!= 3 or on (instance) ((scylla_gossip_live{cluster=\"$cluster\", dc=~\"$dc\"}+1<  bool scalar(count(scylla_node_operation_mode{cluster=\"$cluster\"}==3)))*6 + 3))"
    },
    {
     "expr": "avg(scylla_reactor_utilization{cluster=~\"$cluster\", dc=~\"$dc\"} ) by (instance)"
    },
    {
     "expr": "sum(rate(scylla_reactor_aio_errors{cluster=~\"$cluster\", dc=~\"$dc\"}[$__rate_interval])) by (instance)"
    },
    {
     "expr": "sum(scylla_errors:nodes_total{cluster=~\"$cluster\", dc=~\"$dc\"}) by (instance) >bool 0"
    },
    {
     "dashversion": [
      ">5.2",
      ">2023.1"
     ],
     "expr": "(min(scylla_streaming_finished_percentage{cluster=\"$cluster\", dc=~\"$dc\"}*100) by (instance) < 100) or on (instance)  0*sum(scylla_scylladb_current_version{cluster=\"$cluster\", dc=~\"$dc\"}) by (instance)"
    },
    {
     "expr": "100-100*node_filesystem_avail_bytes{mountpoint=\"$mount_point\",  dc=~\"$dc\", instance=~\"$node\"}/node_filesystem_size_bytes{mountpoint=\"$mount_point\", dc=~\"$dc\", instance=~\"$node\"}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(scylla_alternator_op_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", op=~\"GetItem|PutItem|UpdateItem|DeleteItem\"}[$__rate_interval])>0) by (le, instance))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_alternator_op_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", op=\"GetItem\"}[$__rate_interval])>0) by (le, instance))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_alternator_op_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", op=\"PutItem\"}[$__rate_interval])>0) by (le, instance))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_alternator_op_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", op=\"UpdateItem\"}[$__rate_interval])>0) by (le, instance))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_alternator_op_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", op=\"DeleteItem\"}[$__rate_interval])>0) by (le, instance))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 10, "x": 14, "y": 29 },
   "options": {
    "content": "<img src=\"https://repositories.scylladb.com/scylla/imgversion/$all_scyllas_versions/scylla\"></img>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data Plane Actions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Data Plane Actions</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "GetItem by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"GetItem\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "PutItem by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"PutItem\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "UpdateItem by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"UpdateItem\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "DeleteItem by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"DeleteItem\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Query by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"Query\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Scan by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"Scan\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "BatchWriteItem by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"BatchWriteItem\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Operations from BatchWriteItem by [[by]]",
   "type": "timeseries",
   "description": "The number of items processed as a result of BatchWriteItem",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "dashversion": [
      ">6.2",
      ">2025.1"
     ],
     "expr": "$func(rate(scylla_alternator_batch_item_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"BatchWriteItem\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Average Batch size of BatchWriteItem by [[by]]",
   "type": "timeseries",
   "description": "The average batch size of BatchWriteItem",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "dashversion": [
      ">6.2",
      ">2025.1"
     ],
     "expr": "$func(rate(scylla_alternator_batch_item_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"BatchWriteItem\"}[$__rate_interval])) by ([[by]])/$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"BatchWriteItem\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "BatchGetItem by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"BatchGetItem\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Operations from BatchGetItem by [[by]]",
   "type": "timeseries",
   "description": "The number of items processed as a result of BatchGetItem",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "dashversion": [
      ">6.2",
      ">2025.1"
     ],
     "expr": "$func(rate(scylla_alternator_batch_item_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"BatchGetItem\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Average Batch size of BatchGetItem by [[by]]",
   "type": "timeseries",
   "description": "The average batch size of BatchGetItem",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "dashversion": [
      ">6.2",
      ">2025.1"
     ],
     "expr": "$func(rate(scylla_alternator_batch_item_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"BatchGetItem\"}[$__rate_interval])) by ([[by]])/$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"BatchGetItem\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 57 },
   "options": {
    "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Data Plane Latencies</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "$alternator_latency_ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "repeat": "alternator_latency_ops",
   "targets": [
    {}
   ]
  },
  {
   "title": "Completed $alternator_latency_ops",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_op_latency_summary_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"$alternator_latency_ops\"}[$__rate_interval])) by ([[by]]) or on () $func(rate(scylla_alternator_op_latency_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"$alternator_latency_ops\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Average $alternator_latency_ops latency by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "scylla_alternator_op_latency_summary{quantile=\"0.5\", by=\"$by\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"$alternator_latency_ops\"} or on () $func(rate(scylla_alternator_op_latency_sum{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"$alternator_latency_ops\"}[$__rate_interval])) by ([[by]])/($func(rate(scylla_alternator_op_latency_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"$alternator_latency_ops\"}[$__rate_interval])) by ([[by]]) + 1)"
    }
   ]
  },
  {
   "title": "95th percentile $alternator_latency_ops latency by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "scylla_alternator_op_latency_summary{quantile=\"0.95\", by=\"$by\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"$alternator_latency_ops\"} or on() histogram_quantile(0.95, sum(rate(scylla_alternator_op_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"$alternator_latency_ops\"}[$__rate_interval])) by ([[by]], le))"
    }
   ]
  },
  {
   "title": "99th percentile $alternator_latency_ops latency by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "scylla_alternator_op_latency_summary{quantile=\"0.99\", by=\"$by\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"$alternator_latency_ops\"} or on() histogram_quantile(0.99, sum(rate(scylla_alternator_op_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"$alternator_latency_ops\"}[$__rate_interval])) by ([[by]], le))"
    }
   ]
  },
  {
   "title": "Streams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 102 },
   "options": {
    "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Streams Actions</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "ListStreams by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"ListStreams\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "DescribeStream by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"DescribeStream\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "GetShardIterator by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"GetShardIterator\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "GetRecords by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"GetRecords\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 116 },
   "options": {
    "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Streams Latencies</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "$alternator_streams_latency_ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 },
   "repeat": "alternator_streams_latency_ops",
   "targets": [
    {}
   ]
  },
  {
   "title": "Completed $alternator_streams_latency_ops",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_op_latency_summary_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"$alternator_streams_latency_ops\"}[$__rate_interval])) by ([[by]]) or on() $func(rate(scylla_alternator_op_latency_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"$alternator_streams_latency_ops\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Average $alternator_streams_latency_ops latency by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "scylla_alternator_op_latency_summary{quantile=\"0.5\", by=\"$by\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"$alternator_streams_latency_ops\"} or on() $func(rate(scylla_alternator_op_latency_sum{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"$alternator_streams_latency_ops\"}[$__rate_interval])) by ([[by]])/($func(rate(scylla_alternator_op_latency_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"$alternator_streams_latency_ops\"}[$__rate_interval])) by ([[by]]) + 1)"
    }
   ]
  },
  {
   "title": "95th percentile $alternator_streams_latency_ops latency by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "scylla_alternator_op_latency_summary{quantile=\"0.95\", by=\"$by\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"$alternator_streams_latency_ops\"} or on () histogram_quantile(0.95, sum(rate(scylla_alternator_op_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"$alternator_streams_latency_ops\"}[$__rate_interval])) by ([[by]], le))"
    }
   ]
  },
  {
   "title": "99th percentile $alternator_streams_latency_ops latency by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "scylla_alternator_op_latency_summary{quantile=\"0.99\", by=\"$by\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"$alternator_streams_latency_ops\"} or on () histogram_quantile(0.99, sum(rate(scylla_alternator_op_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"$alternator_streams_latency_ops\"}[$__rate_interval])) by ([[by]], le))"
    }
   ]
  },
  {
   "title": "Control plane",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 126 },
   "options": {
    "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Control Plane Actions</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "CreateTable by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"CreateTable\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "DeleteTable by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"DeleteTable\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "DescribeTable by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"DescribeTable\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "ListTables by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"ListTables\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "DescribeEndpoints by [[by]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_alternator_operation{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", op=\"DescribeEndpoints\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Expired Item Deleted by [[by]]",
   "type": "timeseries",
   "description": "The number of items deleted by their TTL",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_expiration_items_deleted{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 140 },
   "options": {
    "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Cache</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 140 },
   "options": {
    "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Timeouts</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "description": "Number of rows that were read from the cache, without needing to be fetched from storage.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_cache_row_hits{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "timeseries",
   "description": "Number of rows that were not present in the cache, and had to be fetched from storage.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_cache_row_misses{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Write Timeouts/Minutes by [[by]]",
   "type": "timeseries",
   "description": "Requests that Scylla tried to write but timed out. Timeouts are counted in the node that received the request (the coordinator), not at the replicas.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "si:writes/s" } },
   "targets": [
    {
     "expr": "$func(delta(scylla_storage_proxy_coordinator_write_timeouts{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Read Timeouts/Minutes by [[by]]",
   "type": "timeseries",
   "description": "Requests that Scylla tried to read but timed out. Timeouts are counted in the node that received the request (the coordinator), not at the replicas.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "si:reads/m" } },
   "targets": [
    {
     "expr": "$func(delta(scylla_storage_proxy_coordinator_read_timeouts{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 148 },
   "options": {
    "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Your Panels</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Your Graph here",
   "type": "timeseries",
   "description": "This graph panel was left empty on purpose for ad-hoc usage. Change it when needed. Pay attention that changes to the panel will not be saved.\n\nIf you do need a panel that can be saved, create a new dashboard, or edit the panel inside the json file",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Your Graph here",
   "type": "timeseries",
   "description": "This graph panel was left empty on purpose for ad-hoc usage. Change it when needed. Pay attention that changes to the panel will not be saved.\n\nIf you do need a panel that can be saved, create a new dashboard, or edit the panel inside the json file",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 156 },
   "options": {
    "content": "<div style=\"color:#5780C1; border-bottom: 0px solid #5780C1;\">Scylla Monitoring version - 4.9.4</div> <div style=\"\"><a href=\"https://github.com/scylladb/scylla-monitoring/issues/new?body=scylla-version%3D[[scylla_version]]%0Amonitoring-version%3D[[monitoring_version]]%0Adashboard%3D${__dashboard.uid}\" target=\"_blank\">\n<input title=\"Report an issue with Scylla Monitoring\" type=\"button\" style=\"background-color:#306EE6;color:white;border-radius: 15px;font-size:14px;line-height:22px;padding:2px\" value=\"&nbsp;Report an issue on this page&nbsp;\"></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"/render/d/${__dashboard.uid}?orgId=1&from=${__from}&to=${__to}&width=1600&height=-1&kiosk\" target=\"_blank\" download=\"dashboard_${__dashboard.uid}-${__from:date:iso}.png\"><input title=\"Make a Screenshot\" type=\"button\" style=\"background-color:#306EE6;color:white;border-radius: 15px;font-size:14px;line-height:22px;padding:2px\" value=\"&nbsp;&nbsp;&nbsp;Screenshot&nbsp;&nbsp;&nbsp;\"></input></a></span></div>"
   },
   "targets": [
    {}
   ]
  }
 ]
}