{
 "title": "Execution",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Execution Latency p99 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_block_execution_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Execution Latency p50 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_block_execution_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operation Execution Latency p99 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_operation_execution_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operation Execution Latency p50 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_operation_execution_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Execution Latency p99 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_message_execution_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Execution Latency p50 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_message_execution_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytecode decompression latency p99 (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_bytecode_decompression_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytecode decompression latency p50 (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_bytecode_decompression_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State hash computation latency p99 (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_state_hash_computation_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State hash computation latency p50 (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_state_hash_computation_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Chains opened per second (averaged for the past minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(linera_open_chain_count[1m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(linera_open_chain_count[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Blocks added to chains per second (averaged for the past minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(linera_num_blocks[1m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(linera_num_blocks[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Blocks executed per second (averaged for the past minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(linera_num_blocks_executed[1m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(linera_num_blocks_executed[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Transactions per second (averaged for the past minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(linera_transaction_count[1m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(linera_transaction_count[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Operations per second (averaged for the past minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(rate(linera_operation_count[1m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(linera_operation_count[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Incoming bundles per second (averaged for the past minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum(rate(linera_incoming_bundle_count[1m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(linera_incoming_bundle_count[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Concurrent cross chain message tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(linera_cross_chain_message_tasks) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(linera_cross_chain_message_tasks)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Notification channel full per second (averaged for the past minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "rate(linera_notification_channel_full[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certificates signed per second per validator (averaged for the past minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sum(rate(linera_certificates_signed[1m])) by (validator_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cross chain message channel full per second (averaged for the past minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "rate(linera_cross_chain_message_channel_full[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Value cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((\n  sum(rate(linera_value_cache_hit[1m])) by (key_type, value_type) or vector(0)\n)\n/\n(\n  sum(rate(linera_value_cache_hit[1m])) by (key_type, value_type) or vector(0)\n  +\n  sum(rate(linera_value_cache_miss[1m])) by (key_type, value_type) or vector(0)\n)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Rounds in certificate p99 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_num_rounds_in_certificate_bucket[1m])) by (le, certificate_value, round_type))",
     "legendFormat": "{{certificate_value}} - {{round_type}}"
    }
   ]
  },
  {
   "title": "Rounds in certificate p50 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_num_rounds_in_certificate_bucket[1m])) by (le, certificate_value, round_type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of inboxes p99 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_num_inboxes_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of inboxes p50 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_num_inboxes_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of outboxes p99 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_num_outboxes_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of outboxes p50 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_num_outboxes_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inbox size p99 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_inbox_size_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inbox size p50 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_inbox_size_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbox size p99 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_outbox_size_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbox size p50 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_outbox_size_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Removed bundles p99 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_removed_bundles_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Removed bundles p50 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_removed_bundles_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rounds in block proposal p99 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_num_rounds_in_block_proposal_bucket[1m])) by (le, round_type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rounds in block proposal p50 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_num_rounds_in_block_proposal_bucket[1m])) by (le, round_type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certificates signed per validator",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
   "targets": [
    {
     "expr": "sum(linera_certificates_signed) by (validator_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Wasm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 } },
  {
   "title": "Wasm Contract Instantiation Latency p99 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_wasm_contract_instantiation_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wasm Contract Instantiation Latency p50 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_wasm_contract_instantiation_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wasm Service Instantiation Latency p99 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_wasm_service_instantiation_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wasm Service Instantiation Latency p50 ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_wasm_service_instantiation_latency_bucket[1m])) by (le))",
     "legendFormat": "{{pod}} - {{le}}"
    }
   ]
  },
  {
   "title": "Wasm fuel used per block p99 (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_wasm_fuel_used_per_block_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wasm fuel used per block p50 (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_wasm_fuel_used_per_block_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wasm num reads per block p99 (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 180 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_wasm_num_reads_per_block_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wasm num reads per block p50 (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 180 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_wasm_num_reads_per_block_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wasm bytes read per block p99 (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_wasm_bytes_read_per_block_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wasm bytes read per block p50 (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_wasm_bytes_read_per_block_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wasm bytes written per block p99 (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 196 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_wasm_bytes_written_per_block_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wasm bytes written per block p50 (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 196 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_wasm_bytes_written_per_block_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cross chain queue wait time p99 (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(linera_cross_chain_queue_wait_time_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cross chain queue wait time p50 (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(linera_cross_chain_queue_wait_time_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chain worker request queue wait time p99 (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(linera_chain_worker_request_queue_wait_time_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chain worker request queue wait time p50 (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(linera_chain_worker_request_queue_wait_time_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create network actions latency p99 (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(linera_create_network_actions_latency_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create network actions latency p50 (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(linera_create_network_actions_latency_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}