{
 "title": "Views",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Save view per second (averaged for the past minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(linera_save_view[1m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(linera_save_view[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Load view per second (averaged for the past minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(linera_load_view[1m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(linera_load_view[1m])) ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cache hit ratio (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum(rate(linera_num_cache_success[1m])) by (pod)\n    /\n    (\n        sum(rate(linera_num_cache_success[1m])) by (pod)\n        + sum(rate(linera_num_cache_fault[1m])) by (pod)\n    )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}